using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Connects an affiliate program to the given chat. Returns information about the connected affiliate program
        /// </summary>
        public class ConnectChatAffiliateProgram : Function<ChatAffiliateProgram>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "connectChatAffiliateProgram";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Identifier of the chat to which the affiliate program will be connected. Can be an identifier of the Saved Messages chat, of a chat with an owned bot, or of a channel chat with can_post_messages administrator right
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_id")]
            public long ChatId { get; set; }

            /// <summary>
            /// Identifier of the bot, which affiliate program is connected
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("bot_user_id")]
            public long BotUserId { get; set; }
        }

        /// <summary>
        /// Connects an affiliate program to the given chat. Returns information about the connected affiliate program
        /// </summary>
        public static Task<ChatAffiliateProgram> ConnectChatAffiliateProgramAsync(
            this Client client, long chatId = default, long botUserId = default)
        {
            return client.ExecuteAsync(new ConnectChatAffiliateProgram
            {
                ChatId = chatId, BotUserId = botUserId
            });
        }
    }
}
// REUSE-IgnoreEnd