using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Disconnects an affiliate program from the given chat and immediately deactivates its referral link. Returns updated information about the disconnected affiliate program
        /// </summary>
        public class DisconnectChatAffiliateProgram : Function<ChatAffiliateProgram>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "disconnectChatAffiliateProgram";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Identifier of the chat for which the affiliate program is connected
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_id")]
            public long ChatId { get; set; }

            /// <summary>
            /// The referral link of the affiliate program
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("url")]
            public string Url { get; set; }
        }

        /// <summary>
        /// Disconnects an affiliate program from the given chat and immediately deactivates its referral link. Returns updated information about the disconnected affiliate program
        /// </summary>
        public static Task<ChatAffiliateProgram> DisconnectChatAffiliateProgramAsync(
            this Client client, long chatId = default, string url = default)
        {
            return client.ExecuteAsync(new DisconnectChatAffiliateProgram
            {
                ChatId = chatId, Url = url
            });
        }
    }
}
// REUSE-IgnoreEnd