using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Returns an affiliate program that were connected to the given chat by identifier of the bot that created the program
        /// </summary>
        public class GetChatAffiliateProgram : Function<ChatAffiliateProgram>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "getChatAffiliateProgram";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Identifier of the chat for which the affiliate program was connected. Can be an identifier of the Saved Messages chat, of a chat with an owned bot, or of a channel chat with can_post_messages administrator right
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_id")]
            public long ChatId { get; set; }

            /// <summary>
            /// Identifier of the bot that created the program
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("bot_user_id")]
            public long BotUserId { get; set; }
        }

        /// <summary>
        /// Returns an affiliate program that were connected to the given chat by identifier of the bot that created the program
        /// </summary>
        public static Task<ChatAffiliateProgram> GetChatAffiliateProgramAsync(
            this Client client, long chatId = default, long botUserId = default)
        {
            return client.ExecuteAsync(new GetChatAffiliateProgram
            {
                ChatId = chatId, BotUserId = botUserId
            });
        }
    }
}
// REUSE-IgnoreEnd